/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Menu;

/**
 *
 * @author MSI
 */
public class ExportarDatos extends javax.swing.JPanel {
    private Menu menu;
    private VP currentVP;
    
    /**
     * Creates new form ExportarDatos
     */
    public ExportarDatos() {
        initComponents();
    }
    
    public void setCurrentVP(VP vp){
        currentVP = vp;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
        System.out.println(menu.getMenu());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPnl = new javax.swing.JPanel();
        headerLblPnl = new javax.swing.JLabel();
        guardarEventosYAsistentesLbl = new javax.swing.JLabel();
        guardarEventosYAsistentesBtn = new javax.swing.JButton();
        descargarRecintosLbl = new javax.swing.JLabel();
        descargarRecintosBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPnl.setBackground(new java.awt.Color(255, 228, 209));
        backgroundPnl.setPreferredSize(new java.awt.Dimension(768, 578));
        backgroundPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLblPnl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        headerLblPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLblPnl.setText("Haga click el boton \"Guardar\" para descargar los datos que desea");
        headerLblPnl.setPreferredSize(new java.awt.Dimension(400, 65));
        backgroundPnl.add(headerLblPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 730, 110));

        guardarEventosYAsistentesLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guardarEventosYAsistentesLbl.setText("Guardar todos los datos de Eventos en Formato CSV");
        backgroundPnl.add(guardarEventosYAsistentesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        guardarEventosYAsistentesBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        guardarEventosYAsistentesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/saveFileIcon.png"))); // NOI18N
        guardarEventosYAsistentesBtn.setText("Guardar");
        guardarEventosYAsistentesBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        guardarEventosYAsistentesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarEventosYAsistentesBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(guardarEventosYAsistentesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        descargarRecintosLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        descargarRecintosLbl.setText("Guardar todos los datos de Recintos en Formato CSV");
        backgroundPnl.add(descargarRecintosLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        descargarRecintosBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descargarRecintosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/saveFileIcon.png"))); // NOI18N
        descargarRecintosBtn.setText("Guardar");
        descargarRecintosBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        descargarRecintosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descargarRecintosBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(descargarRecintosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        add(backgroundPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void guardarEventosYAsistentesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarEventosYAsistentesBtnActionPerformed
        menu.guardarDatosMapaEventos();
    }//GEN-LAST:event_guardarEventosYAsistentesBtnActionPerformed

    private void descargarRecintosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descargarRecintosBtnActionPerformed
        menu.guardarDatosArrayListRecintos();
    }//GEN-LAST:event_descargarRecintosBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPnl;
    private javax.swing.JButton descargarRecintosBtn;
    private javax.swing.JLabel descargarRecintosLbl;
    private javax.swing.JButton guardarEventosYAsistentesBtn;
    private javax.swing.JLabel guardarEventosYAsistentesLbl;
    private javax.swing.JLabel headerLblPnl;
    // End of variables declaration//GEN-END:variables
}
