/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Evento;
import Modelo.Asistente;
import Modelo.Menu;
import Exceptions.BadIdAsistenteException;
import Exceptions.BadRangeEdadException;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */

/*
    POR FAVOR LEER LA NOMENCLATURA DE FUNCIONES, JBUTTONS Y DEMAS.
    PARA ELLO, PUEDEN ENCONTRARLA MAS ABAJO EN LA LINEA 342 Y ASI ENTENDER QUE CONTROLA CADA FUNCION
*/

public class GestionEntradasEventos extends javax.swing.JPanel {

    /**
     * Creates new form GestionEntradasEventos
     */
    private Asistente currentAsistente = new Asistente();
    private Evento currentEvento = new Evento();
    private Menu menu;
    private VP currentVP;
    
    //Constructor de GestionEntradasEventos. Oculta los paneles asociados a cada JButton Principal.
    public GestionEntradasEventos() {
        initComponents();
        venderEntradasPnl.setVisible(false);
        cancelEntradaPnl.setVisible(false);
        datosAsistentePnl.setVisible(false);
    }
    
    //============================ Setters para las instancias actuales de Menu y VP ============================
    
    public void setCurrentVP(VP vp){
        currentVP = vp;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
        System.out.println(menu.getMenu());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPnl = new javax.swing.JPanel();
        headerLblPnl = new javax.swing.JLabel();
        datosAsistentePnl = new javax.swing.JPanel();
        headerLblDA = new javax.swing.JLabel();
        idAsistenteLblDA = new javax.swing.JLabel();
        idAsistenteFieldDA = new javax.swing.JTextField();
        nombreAsistLblDA = new javax.swing.JLabel();
        nombreAsistFieldDA = new javax.swing.JTextField();
        edadAsistLblDA = new javax.swing.JLabel();
        edadAsistFieldDA = new javax.swing.JTextField();
        emailLblDA = new javax.swing.JLabel();
        emailFieldDA = new javax.swing.JTextField();
        realizarVentaBtnDA = new javax.swing.JButton();
        venderEntradasPnl = new javax.swing.JPanel();
        headeLblVE = new javax.swing.JLabel();
        idEventoLblVE = new javax.swing.JLabel();
        idEventoFieldVE = new javax.swing.JTextField();
        backBtnVEPnl = new javax.swing.JButton();
        validarIdEventoBtnVE = new javax.swing.JButton();
        cancelEntradaPnl = new javax.swing.JPanel();
        headerValidarIdEventoLblCE = new javax.swing.JLabel();
        headerLblCE = new javax.swing.JLabel();
        idAsistLblCE = new javax.swing.JLabel();
        idAsistFieldCE = new javax.swing.JTextField();
        idEventoLblCE = new javax.swing.JLabel();
        idEventoFieldCE = new javax.swing.JTextField();
        backBtnCEPnl = new javax.swing.JButton();
        reembolsarBtnCE = new javax.swing.JButton();
        validarIdEventoBtnCE = new javax.swing.JButton();
        venderEntradasBtn = new javax.swing.JButton();
        CancelarEntradaBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(768, 578));
        setVerifyInputWhenFocusTarget(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPnl.setBackground(new java.awt.Color(255, 228, 209));
        backgroundPnl.setPreferredSize(new java.awt.Dimension(768, 578));
        backgroundPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLblPnl.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        headerLblPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLblPnl.setText("Seleccione una opcion para Gestionar las Entradas");
        backgroundPnl.add(headerLblPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 640, 110));

        datosAsistentePnl.setBackground(new java.awt.Color(255, 255, 255));
        datosAsistentePnl.setPreferredSize(new java.awt.Dimension(710, 440));
        datosAsistentePnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLblDA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headerLblDA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLblDA.setText("Por favor, ingrese los datos del Asistente");
        headerLblDA.setPreferredSize(new java.awt.Dimension(480, 65));
        datosAsistentePnl.add(headerLblDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        idAsistenteLblDA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idAsistenteLblDA.setText("ID del Asistente (Formato \"A0\")");
        datosAsistentePnl.add(idAsistenteLblDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        idAsistenteFieldDA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idAsistenteFieldDA.setPreferredSize(new java.awt.Dimension(91, 22));
        datosAsistentePnl.add(idAsistenteFieldDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        nombreAsistLblDA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreAsistLblDA.setText("Nombre del Asistente (Nombre, Apellido Paterno)");
        datosAsistentePnl.add(nombreAsistLblDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        nombreAsistFieldDA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreAsistFieldDA.setPreferredSize(new java.awt.Dimension(91, 22));
        nombreAsistFieldDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAsistFieldDAActionPerformed(evt);
            }
        });
        datosAsistentePnl.add(nombreAsistFieldDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        edadAsistLblDA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edadAsistLblDA.setText("Edad");
        datosAsistentePnl.add(edadAsistLblDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        edadAsistFieldDA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edadAsistFieldDA.setPreferredSize(new java.awt.Dimension(91, 22));
        edadAsistFieldDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadAsistFieldDAActionPerformed(evt);
            }
        });
        datosAsistentePnl.add(edadAsistFieldDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        emailLblDA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailLblDA.setText("Emaill");
        datosAsistentePnl.add(emailLblDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        emailFieldDA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailFieldDA.setPreferredSize(new java.awt.Dimension(91, 22));
        emailFieldDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldDAActionPerformed(evt);
            }
        });
        datosAsistentePnl.add(emailFieldDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        realizarVentaBtnDA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        realizarVentaBtnDA.setText("Realizar Venta");
        realizarVentaBtnDA.setPreferredSize(new java.awt.Dimension(128, 30));
        realizarVentaBtnDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVentaBtnDAActionPerformed(evt);
            }
        });
        datosAsistentePnl.add(realizarVentaBtnDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        backgroundPnl.add(datosAsistentePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        venderEntradasPnl.setBackground(new java.awt.Color(255, 255, 255));
        venderEntradasPnl.setPreferredSize(new java.awt.Dimension(710, 440));
        venderEntradasPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headeLblVE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headeLblVE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headeLblVE.setText("Por favor, ingrese del ID del Evento para la venta");
        headeLblVE.setPreferredSize(new java.awt.Dimension(480, 65));
        venderEntradasPnl.add(headeLblVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        idEventoLblVE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idEventoLblVE.setText("ID del Evento");
        venderEntradasPnl.add(idEventoLblVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        idEventoFieldVE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idEventoFieldVE.setPreferredSize(new java.awt.Dimension(91, 22));
        venderEntradasPnl.add(idEventoFieldVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        backBtnVEPnl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backBtnVEPnl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/orangeGoBackArrow.png"))); // NOI18N
        backBtnVEPnl.setText("Atras");
        backBtnVEPnl.setPreferredSize(new java.awt.Dimension(128, 30));
        backBtnVEPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnVEPnlActionPerformed(evt);
            }
        });
        venderEntradasPnl.add(backBtnVEPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        validarIdEventoBtnVE.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        validarIdEventoBtnVE.setText("Validar ID");
        validarIdEventoBtnVE.setPreferredSize(new java.awt.Dimension(75, 43));
        validarIdEventoBtnVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarIdEventoBtnVEActionPerformed(evt);
            }
        });
        venderEntradasPnl.add(validarIdEventoBtnVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        backgroundPnl.add(venderEntradasPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        cancelEntradaPnl.setBackground(new java.awt.Color(255, 255, 255));
        cancelEntradaPnl.setPreferredSize(new java.awt.Dimension(710, 440));
        cancelEntradaPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerValidarIdEventoLblCE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headerValidarIdEventoLblCE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerValidarIdEventoLblCE.setText("Por favor, ingrese el ID del Evento donde se encuentra el asistente");
        headerValidarIdEventoLblCE.setPreferredSize(new java.awt.Dimension(600, 65));
        cancelEntradaPnl.add(headerValidarIdEventoLblCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        headerLblCE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headerLblCE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLblCE.setText("Por favor, ingrese el ID del Asistente para Reembolsar");
        headerLblCE.setPreferredSize(new java.awt.Dimension(480, 65));
        cancelEntradaPnl.add(headerLblCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        idAsistLblCE.setText("ID del Asistente");
        cancelEntradaPnl.add(idAsistLblCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        idAsistFieldCE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idAsistFieldCE.setPreferredSize(new java.awt.Dimension(91, 22));
        idAsistFieldCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAsistFieldCEActionPerformed(evt);
            }
        });
        cancelEntradaPnl.add(idAsistFieldCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        idEventoLblCE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idEventoLblCE.setText("ID del Evento");
        cancelEntradaPnl.add(idEventoLblCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        idEventoFieldCE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idEventoFieldCE.setPreferredSize(new java.awt.Dimension(91, 22));
        cancelEntradaPnl.add(idEventoFieldCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        backBtnCEPnl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backBtnCEPnl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/orangeGoBackArrow.png"))); // NOI18N
        backBtnCEPnl.setText("Atras");
        backBtnCEPnl.setPreferredSize(new java.awt.Dimension(128, 30));
        backBtnCEPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnCEPnlActionPerformed(evt);
            }
        });
        cancelEntradaPnl.add(backBtnCEPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        reembolsarBtnCE.setText("Reembolsar");
        reembolsarBtnCE.setPreferredSize(new java.awt.Dimension(128, 30));
        reembolsarBtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reembolsarBtnCEActionPerformed(evt);
            }
        });
        cancelEntradaPnl.add(reembolsarBtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        validarIdEventoBtnCE.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        validarIdEventoBtnCE.setText("Validar ID");
        validarIdEventoBtnCE.setPreferredSize(new java.awt.Dimension(75, 43));
        validarIdEventoBtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarIdEventoBtnCEActionPerformed(evt);
            }
        });
        cancelEntradaPnl.add(validarIdEventoBtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        backgroundPnl.add(cancelEntradaPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        venderEntradasBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        venderEntradasBtn.setText("Vender Entradas para un Evento");
        venderEntradasBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        venderEntradasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderEntradasBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(venderEntradasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        CancelarEntradaBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CancelarEntradaBtn.setText("Cancelar Entrada y Reembolsar Asistente");
        CancelarEntradaBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        CancelarEntradaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarEntradaBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(CancelarEntradaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        add(backgroundPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    //============================ JButtons Principales del Panel GestionEntradaEventos ============================
    
    private void CancelarEntradaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarEntradaBtnActionPerformed
        cancelEntradaPnl.setVisible(true);
        venderEntradasBtn.setVisible(false);
        CancelarEntradaBtn.setVisible(false);
        headerLblCE.setVisible(false);
        idAsistLblCE.setVisible(false);
        idAsistFieldCE.setVisible(false);
        idEventoLblCE.setVisible(true);
        idEventoFieldCE.setVisible(true);
        reembolsarBtnCE.setVisible(false);
        currentVP.ventaEntradasBtn.setVisible(false);
        currentVP.eventosBtn.setVisible(false);
        currentVP.recintosBtn.setVisible(false);
        currentVP.exitBtn.setVisible(false);
        currentVP.homeBtn.setVisible(false);
        currentVP.exportarDatosBtn.setVisible(false);
    }//GEN-LAST:event_CancelarEntradaBtnActionPerformed

    private void venderEntradasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderEntradasBtnActionPerformed
        venderEntradasPnl.setVisible(true);
        venderEntradasBtn.setVisible(false);
        CancelarEntradaBtn.setVisible(false);
        datosAsistentePnl.setVisible(false);
        currentVP.ventaEntradasBtn.setVisible(false);
        currentVP.eventosBtn.setVisible(false);
        currentVP.recintosBtn.setVisible(false);
        currentVP.exitBtn.setVisible(false);
        currentVP.homeBtn.setVisible(false);
        currentVP.exportarDatosBtn.setVisible(false);
    }//GEN-LAST:event_venderEntradasBtnActionPerformed
   
    //============= Funciones de Retorno (backBtn), JButtons y JTextFields que interactuan con el usuario ===============
    
    /*
        NOMENCLATURA PARA LEER FUNCIONES:
    
        backBtn*SIGLA*: JButton que devuelve al panel principal de GestionEntradasEventos. (ej: backBtnVE)
        aceptarBtn*SIGLA* - validarIDBtn*SIGLA* - buscarBtn*SIGLA*: JButton que registra la entrada y salida de datos en la ventana. (ej: validarIdEventoBtn)
        clearFields*NOMBRE*: Funcion que limpia los campos JTextFields de funciones especificas. (ej: clearFieldsCancelEntrada)
        *NOMBRE*Field*SIGLA*: JTextField que guarda una String con datos ingresados por el usuario. (ej: idEventoFieldVE)
        *NOMBRECOMPLETO*Btn: JButtons principales del panel GestionEntradasEventos. (ej: venderEntradasBtn)
    
        SIGLAS:
        CE = Cancelar Entrada
        VE = Vender Entrada
        DA = DatosAsistente
    */
    
    private void backBtnCEPnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnCEPnlActionPerformed
        cancelEntradaPnl.setVisible(false);
        venderEntradasBtn.setVisible(true);
        CancelarEntradaBtn.setVisible(true);
        currentVP.ventaEntradasBtn.setVisible(true);
        currentVP.eventosBtn.setVisible(true);
        currentVP.recintosBtn.setVisible(true);
        currentVP.exitBtn.setVisible(true);
        currentVP.homeBtn.setVisible(true);
        currentVP.exportarDatosBtn.setVisible(true);
        clearFieldsCancelEntrada();
    }//GEN-LAST:event_backBtnCEPnlActionPerformed

    private void idAsistFieldCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAsistFieldCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAsistFieldCEActionPerformed

    private void backBtnVEPnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnVEPnlActionPerformed
        // TODO add your handling code here:
        venderEntradasPnl.setVisible(false);
        venderEntradasBtn.setVisible(true);
        CancelarEntradaBtn.setVisible(true);
        currentVP.ventaEntradasBtn.setVisible(true);
        currentVP.eventosBtn.setVisible(true);
        currentVP.recintosBtn.setVisible(true);
        currentVP.exitBtn.setVisible(true);
        currentVP.homeBtn.setVisible(true);
        currentVP.exportarDatosBtn.setVisible(true);
        clearFieldsVenderEntradas();
    }//GEN-LAST:event_backBtnVEPnlActionPerformed

    private void nombreAsistFieldDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAsistFieldDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreAsistFieldDAActionPerformed

    private void edadAsistFieldDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadAsistFieldDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadAsistFieldDAActionPerformed

    private void emailFieldDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldDAActionPerformed

    private void validarIdEventoBtnVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarIdEventoBtnVEActionPerformed
        if(!"".equals(idEventoFieldVE.getText()) && menu.checkEvento(idEventoFieldVE.getText())){
            currentEvento = menu.obtenerEvento(idEventoFieldVE.getText());
            if (menu.obtenerRecinto(currentEvento.getidRecinto()) != null){
                if (currentEvento.getSizeArrayAsistentes() < menu.obtenerRecinto(currentEvento.getidRecinto()).getCupos()){
                    clearFieldsVenderEntradas();
                    datosAsistentePnl.setVisible(true);
                    venderEntradasPnl.setVisible(false);
                }
                else{
                    JOptionPane.showMessageDialog(null, "ENTRADAS AGOTADAS");
                    clearFieldsVenderEntradas();
                    venderEntradasPnl.setVisible(false);
                    venderEntradasBtn.setVisible(true);
                    CancelarEntradaBtn.setVisible(true);
                    currentVP.ventaEntradasBtn.setVisible(true);
                    currentVP.eventosBtn.setVisible(true);
                    currentVP.recintosBtn.setVisible(true);
                    currentVP.exitBtn.setVisible(true);
                    currentVP.homeBtn.setVisible(true);
                    currentVP.exportarDatosBtn.setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "El ID ingresado corresponde a un Evento sin Recinto asignado. La venta de entradas para este recinto queda inhabilitada hasta nuevo aviso.", "Recinto Availability", JOptionPane.ERROR_MESSAGE);
                venderEntradasPnl.setVisible(false);
                venderEntradasBtn.setVisible(true);
                CancelarEntradaBtn.setVisible(true);
                currentVP.ventaEntradasBtn.setVisible(true);
                currentVP.eventosBtn.setVisible(true);
                currentVP.recintosBtn.setVisible(true);
                currentVP.exitBtn.setVisible(true);
                currentVP.homeBtn.setVisible(true);
                currentVP.exportarDatosBtn.setVisible(true);
                clearFieldsVenderEntradas();
            }
        }
        else{
            clearFieldsVenderEntradas();
            JOptionPane.showMessageDialog(null, "No Existe un Evento asociado a este ID", "ID Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_validarIdEventoBtnVEActionPerformed

    private void realizarVentaBtnDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVentaBtnDAActionPerformed
        if (!"".equals(idAsistenteFieldDA.getText()) && 
            !"".equals(nombreAsistFieldDA.getText()) && 
            !"".equals(edadAsistFieldDA.getText()) && 
            !"".equals(emailFieldDA.getText())) {
            if (currentEvento.obtenerAsistente(idAsistenteFieldDA.getText()) == null){
                try{
                    currentEvento.ventaEntrada(idAsistenteFieldDA.getText(),nombreAsistFieldDA.getText(),emailFieldDA.getText(),edadAsistFieldDA.getText());
                    datosAsistentePnl.setVisible(false);
                    venderEntradasPnl.setVisible(false);
                    venderEntradasBtn.setVisible(true);
                    CancelarEntradaBtn.setVisible(true);
                    currentVP.ventaEntradasBtn.setVisible(true);
                    currentVP.eventosBtn.setVisible(true);
                    currentVP.recintosBtn.setVisible(true);
                    currentVP.exitBtn.setVisible(true);
                    currentVP.homeBtn.setVisible(true);
                    currentVP.exportarDatosBtn.setVisible(true);
                    clearFieldsVenderEntradas();
                    clearFieldsDatosAsistente();
                    JOptionPane.showMessageDialog(null, "Venta de entrada exitosa. Se ha agregado el Asistente al evento correctamente.");  
                }catch(BadIdAsistenteException e){
                    JOptionPane.showMessageDialog(null, e.getMessage(), "ID Error", JOptionPane.ERROR_MESSAGE);
                }catch(BadRangeEdadException e){
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Edad Error", JOptionPane.ERROR_MESSAGE);
                }catch(IllegalArgumentException e){
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Edad Error", JOptionPane.ERROR_MESSAGE);
                }
                
            }
            else{
                JOptionPane.showMessageDialog(null, "El asistente ingresado ya se encuentra en la lista de asistentes a este Evento", "Duplicate ID", JOptionPane.ERROR_MESSAGE);
                datosAsistentePnl.setVisible(false);
                venderEntradasPnl.setVisible(false);
                venderEntradasBtn.setVisible(true);
                CancelarEntradaBtn.setVisible(true);
                currentVP.ventaEntradasBtn.setVisible(true);
                currentVP.eventosBtn.setVisible(true);
                currentVP.recintosBtn.setVisible(true);
                currentVP.exitBtn.setVisible(true);
                currentVP.homeBtn.setVisible(true);
                currentVP.exportarDatosBtn.setVisible(true);
                clearFieldsVenderEntradas();
                clearFieldsDatosAsistente();
                return;
            }
        }
        else{
           JOptionPane.showMessageDialog(null, "Los campos se encuentran vacios", "Field Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_realizarVentaBtnDAActionPerformed

    private void reembolsarBtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reembolsarBtnCEActionPerformed
        if (!"".equals(idAsistFieldCE.getText())){
            if (currentEvento.obtenerAsistente(idAsistFieldCE.getText()) != null){
                if (currentEvento.eliminarAsistente(idAsistFieldCE.getText())){
                    cancelEntradaPnl.setVisible(false);
                    venderEntradasBtn.setVisible(true);
                    CancelarEntradaBtn.setVisible(true);
                    currentVP.ventaEntradasBtn.setVisible(true);
                    currentVP.eventosBtn.setVisible(true);
                    currentVP.recintosBtn.setVisible(true);
                    currentVP.exitBtn.setVisible(true);
                    currentVP.homeBtn.setVisible(true);
                    currentVP.exportarDatosBtn.setVisible(true);
                    backBtnCEPnl.setVisible(true);
                    validarIdEventoBtnCE.setVisible(true);
                    headerValidarIdEventoLblCE.setVisible(true);
                    clearFieldsVenderEntradas();
                    clearFieldsVenderEntradas();
                    JOptionPane.showMessageDialog(null, "Reembolso exitoso. El asistente fue removido del evento y sus fondos reembolsados correctamente", "System Says",JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "El asistente no pudo ser reembolsado ni removido del evento. Intente mas tarde.", "Unknown Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "El ID ingresado no corresponde a ningun asistente dentro del evento", "Field Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Los campos se encuentran vacios", "Field Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_reembolsarBtnCEActionPerformed

    private void validarIdEventoBtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarIdEventoBtnCEActionPerformed
        if(!"".equals(idEventoFieldCE.getText()) && menu.checkEvento(idEventoFieldCE.getText())){
            currentEvento = menu.obtenerEvento(idEventoFieldCE.getText());
            idEventoLblCE.setVisible(false);
            idEventoFieldCE.setVisible(false);
            validarIdEventoBtnCE.setVisible(false);
            headerValidarIdEventoLblCE.setVisible(false);
            backBtnCEPnl.setVisible(false);
            idAsistLblCE.setVisible(true);
            idAsistFieldCE.setVisible(true);
            reembolsarBtnCE.setVisible(true);
            headerLblCE.setVisible(true);
            clearFieldsVenderEntradas();
        }
        else{
            clearFieldsVenderEntradas();
            JOptionPane.showMessageDialog(null, "No Existe un Evento asociado a este ID");
        }
    }//GEN-LAST:event_validarIdEventoBtnCEActionPerformed
    
    //============================ Funciones de limpiado de campos tipo JTextField ============================
    
    public void clearFieldsCancelEntrada() {
        idAsistFieldCE.setText("");
        idEventoFieldCE.setText("");
    }
    
    public void clearFieldsVenderEntradas() {
        idEventoFieldVE.setText("");
    }
    
    public void clearFieldsDatosAsistente() {
        idAsistenteFieldDA.setText("");
        nombreAsistFieldDA.setText("");
        edadAsistFieldDA.setText("");
        emailFieldDA.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarEntradaBtn;
    private javax.swing.JButton backBtnCEPnl;
    private javax.swing.JButton backBtnVEPnl;
    private javax.swing.JPanel backgroundPnl;
    private javax.swing.JPanel cancelEntradaPnl;
    private javax.swing.JPanel datosAsistentePnl;
    private javax.swing.JTextField edadAsistFieldDA;
    private javax.swing.JLabel edadAsistLblDA;
    private javax.swing.JTextField emailFieldDA;
    private javax.swing.JLabel emailLblDA;
    private javax.swing.JLabel headeLblVE;
    private javax.swing.JLabel headerLblCE;
    private javax.swing.JLabel headerLblDA;
    private javax.swing.JLabel headerLblPnl;
    private javax.swing.JLabel headerValidarIdEventoLblCE;
    private javax.swing.JTextField idAsistFieldCE;
    private javax.swing.JLabel idAsistLblCE;
    private javax.swing.JTextField idAsistenteFieldDA;
    private javax.swing.JLabel idAsistenteLblDA;
    private javax.swing.JTextField idEventoFieldCE;
    private javax.swing.JTextField idEventoFieldVE;
    private javax.swing.JLabel idEventoLblCE;
    private javax.swing.JLabel idEventoLblVE;
    private javax.swing.JTextField nombreAsistFieldDA;
    private javax.swing.JLabel nombreAsistLblDA;
    private javax.swing.JButton realizarVentaBtnDA;
    private javax.swing.JButton reembolsarBtnCE;
    private javax.swing.JButton validarIdEventoBtnCE;
    private javax.swing.JButton validarIdEventoBtnVE;
    private javax.swing.JButton venderEntradasBtn;
    private javax.swing.JPanel venderEntradasPnl;
    // End of variables declaration//GEN-END:variables
}
