/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author MSI
 */
public class GestionEventos extends javax.swing.JPanel {

    /**
     * Creates new form GestionEventos
     */
    public GestionEventos() {
        initComponents();
        crearEventoPnl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPnl = new javax.swing.JPanel();
        headerPnl = new javax.swing.JLabel();
        crearEventoPnl = new javax.swing.JPanel();
        headerVELbl = new javax.swing.JLabel();
        idEventoLbl = new javax.swing.JLabel();
        idEventoField = new javax.swing.JTextField();
        nombreLbl = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        fechaLbl = new javax.swing.JLabel();
        fechaField = new javax.swing.JTextField();
        descripLbl = new javax.swing.JLabel();
        descripField = new javax.swing.JTextField();
        grupoLbl = new javax.swing.JLabel();
        grupoScrollPnl = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        valorEntradaLbl = new javax.swing.JLabel();
        valorEntradaField = new javax.swing.JTextField();
        idRecintoLbl = new javax.swing.JLabel();
        idRecintoField = new javax.swing.JTextField();
        backBtnCEPnl = new javax.swing.JButton();
        crearEventoBtn = new javax.swing.JButton();
        listarEventosBtn = new javax.swing.JButton();
        modEventoBtn = new javax.swing.JButton();
        eliminarEventoBtn = new javax.swing.JButton();
        listarAsistentesBtn = new javax.swing.JButton();
        modAsistenteBtn = new javax.swing.JButton();
        recaudEventoBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPnl.setBackground(new java.awt.Color(255, 228, 209));
        backgroundPnl.setPreferredSize(new java.awt.Dimension(768, 578));
        backgroundPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPnl.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        headerPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerPnl.setText("Seleccione una opcion para Gestionar Eventos");
        headerPnl.setPreferredSize(new java.awt.Dimension(640, 110));
        backgroundPnl.add(headerPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        crearEventoPnl.setBackground(new java.awt.Color(255, 255, 255));
        crearEventoPnl.setPreferredSize(new java.awt.Dimension(710, 440));
        crearEventoPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerVELbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headerVELbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerVELbl.setText("Por favor, ingrese los datos asociados al Evento");
        headerVELbl.setPreferredSize(new java.awt.Dimension(400, 65));
        crearEventoPnl.add(headerVELbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        idEventoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idEventoLbl.setText("ID del Evento");
        crearEventoPnl.add(idEventoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        idEventoField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idEventoField.setPreferredSize(new java.awt.Dimension(91, 22));
        idEventoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEventoFieldActionPerformed(evt);
            }
        });
        crearEventoPnl.add(idEventoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        nombreLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreLbl.setText("Nombre del Evento");
        crearEventoPnl.add(nombreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        nombreField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreField.setPreferredSize(new java.awt.Dimension(91, 22));
        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });
        crearEventoPnl.add(nombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        fechaLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fechaLbl.setText("Fecha del Evento");
        crearEventoPnl.add(fechaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        fechaField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fechaField.setPreferredSize(new java.awt.Dimension(91, 22));
        fechaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaFieldActionPerformed(evt);
            }
        });
        crearEventoPnl.add(fechaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        descripLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descripLbl.setText("Descripcion del Evento");
        crearEventoPnl.add(descripLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        descripField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descripField.setMinimumSize(new java.awt.Dimension(91, 22));
        descripField.setPreferredSize(new java.awt.Dimension(91, 22));
        descripField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripFieldActionPerformed(evt);
            }
        });
        crearEventoPnl.add(descripField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        grupoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        grupoLbl.setText("Seleccione un Grupo Objetivo para el Evento");
        crearEventoPnl.add(grupoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Infantes", "Adolescentes", "Adultos Jovenes", "Adultos", "Tercera Edad" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        grupoScrollPnl.setViewportView(jList1);

        crearEventoPnl.add(grupoScrollPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 110, 100));

        valorEntradaLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valorEntradaLbl.setText("Valor de Entrada del Evento (CLP)");
        crearEventoPnl.add(valorEntradaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        valorEntradaField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valorEntradaField.setPreferredSize(new java.awt.Dimension(91, 22));
        valorEntradaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorEntradaFieldActionPerformed(evt);
            }
        });
        crearEventoPnl.add(valorEntradaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        idRecintoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idRecintoLbl.setText("ID del Recinto donde se alojara el Evento");
        crearEventoPnl.add(idRecintoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        idRecintoField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idRecintoField.setPreferredSize(new java.awt.Dimension(91, 22));
        idRecintoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idRecintoFieldActionPerformed(evt);
            }
        });
        crearEventoPnl.add(idRecintoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        backBtnCEPnl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backBtnCEPnl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/orangeGoBackArrow.png"))); // NOI18N
        backBtnCEPnl.setText("Atras");
        backBtnCEPnl.setPreferredSize(new java.awt.Dimension(128, 30));
        backBtnCEPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnCEPnlActionPerformed(evt);
            }
        });
        crearEventoPnl.add(backBtnCEPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        backgroundPnl.add(crearEventoPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        crearEventoBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        crearEventoBtn.setText("Crear un Evento");
        crearEventoBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        crearEventoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEventoBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(crearEventoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        listarEventosBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listarEventosBtn.setText("Listado de Eventos");
        listarEventosBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        listarEventosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarEventosBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(listarEventosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 165, -1, -1));

        modEventoBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modEventoBtn.setText("Modificar un Evento");
        modEventoBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        modEventoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modEventoBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(modEventoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        eliminarEventoBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eliminarEventoBtn.setText("Eliminar un Evento");
        eliminarEventoBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        eliminarEventoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEventoBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(eliminarEventoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 295, -1, -1));

        listarAsistentesBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listarAsistentesBtn.setText("Listado de Asistentes a un Evento");
        listarAsistentesBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        listarAsistentesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarAsistentesBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(listarAsistentesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        modAsistenteBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modAsistenteBtn.setText("Modificar Datos de un Asistente");
        modAsistenteBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        modAsistenteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modAsistenteBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(modAsistenteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 425, -1, -1));

        recaudEventoBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recaudEventoBtn.setText("Ver Recaudacion de un Evento");
        recaudEventoBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        recaudEventoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recaudEventoBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(recaudEventoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        add(backgroundPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    //================= BOTONES ================================================
    
    private void crearEventoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEventoBtnActionPerformed
        crearEventoPnl.setVisible(true);
        crearEventoBtn.setVisible(false);
        listarEventosBtn.setVisible(false);
        modEventoBtn.setVisible(false);
        eliminarEventoBtn.setVisible(false);
        listarAsistentesBtn.setVisible(false);
        modAsistenteBtn.setVisible(false);
        recaudEventoBtn.setVisible(false);
    }//GEN-LAST:event_crearEventoBtnActionPerformed

    private void listarEventosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarEventosBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarEventosBtnActionPerformed

    private void modEventoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modEventoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modEventoBtnActionPerformed

    private void eliminarEventoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEventoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarEventoBtnActionPerformed

    private void listarAsistentesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarAsistentesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarAsistentesBtnActionPerformed

    private void modAsistenteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modAsistenteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modAsistenteBtnActionPerformed

    private void recaudEventoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recaudEventoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recaudEventoBtnActionPerformed

    //==========================================================================
    
    private void idEventoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEventoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEventoFieldActionPerformed

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void fechaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaFieldActionPerformed

    private void descripFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripFieldActionPerformed

    private void valorEntradaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorEntradaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorEntradaFieldActionPerformed

    private void backBtnCEPnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnCEPnlActionPerformed
        crearEventoPnl.setVisible(false);
        crearEventoBtn.setVisible(true);
        listarEventosBtn.setVisible(true);
        modEventoBtn.setVisible(true);
        eliminarEventoBtn.setVisible(true);
        listarAsistentesBtn.setVisible(true);
        modAsistenteBtn.setVisible(true);
        recaudEventoBtn.setVisible(true);
    }//GEN-LAST:event_backBtnCEPnlActionPerformed

    private void idRecintoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idRecintoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idRecintoFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtnCEPnl;
    private javax.swing.JPanel backgroundPnl;
    private javax.swing.JButton crearEventoBtn;
    private javax.swing.JPanel crearEventoPnl;
    private javax.swing.JTextField descripField;
    private javax.swing.JLabel descripLbl;
    private javax.swing.JButton eliminarEventoBtn;
    private javax.swing.JTextField fechaField;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JLabel grupoLbl;
    private javax.swing.JScrollPane grupoScrollPnl;
    private javax.swing.JLabel headerPnl;
    private javax.swing.JLabel headerVELbl;
    private javax.swing.JTextField idEventoField;
    private javax.swing.JLabel idEventoLbl;
    private javax.swing.JTextField idRecintoField;
    private javax.swing.JLabel idRecintoLbl;
    private javax.swing.JList<String> jList1;
    private javax.swing.JButton listarAsistentesBtn;
    private javax.swing.JButton listarEventosBtn;
    private javax.swing.JButton modAsistenteBtn;
    private javax.swing.JButton modEventoBtn;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JButton recaudEventoBtn;
    private javax.swing.JTextField valorEntradaField;
    private javax.swing.JLabel valorEntradaLbl;
    // End of variables declaration//GEN-END:variables
}
