/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author MSI
 */
public class GestionRecintos extends javax.swing.JPanel {

    /**
     * Creates new form GestionRecintos
     */
    public GestionRecintos() {
        initComponents();
        crearRecintoPnl.setVisible(false);
        listarRecintosPnl.setVisible(false);
        modRecintoPnl.setVisible(false);
        eliminarRecintoPnl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPnl = new javax.swing.JPanel();
        headerLbl = new javax.swing.JLabel();
        crearRecintoPnl = new javax.swing.JPanel();
        headerCRLbl = new javax.swing.JLabel();
        idRecintoLbl = new javax.swing.JLabel();
        idRecintoField = new javax.swing.JTextField();
        nombreRecintoLbl = new javax.swing.JLabel();
        nombreRecintoField = new javax.swing.JTextField();
        ubicacionLbl = new javax.swing.JLabel();
        ubicacionField = new javax.swing.JTextField();
        capacidadLbl = new javax.swing.JLabel();
        capacidadField = new javax.swing.JTextField();
        backBtnCRPnl = new javax.swing.JButton();
        listarRecintosPnl = new javax.swing.JPanel();
        headerVELbl = new javax.swing.JLabel();
        idEventoLbl = new javax.swing.JLabel();
        idEventoField = new javax.swing.JTextField();
        idAsistenteLbl = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        nombreAsistLbl = new javax.swing.JLabel();
        nombreAsistField = new javax.swing.JTextField();
        edadLbl = new javax.swing.JLabel();
        edadField = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        backBtnLRPnl = new javax.swing.JButton();
        modRecintoPnl = new javax.swing.JPanel();
        headerMRLbl = new javax.swing.JLabel();
        idRecintoLblMR = new javax.swing.JLabel();
        idRecintoFieldMR = new javax.swing.JTextField();
        backBtnMRPnl = new javax.swing.JButton();
        eliminarRecintoPnl = new javax.swing.JPanel();
        headerERLbl = new javax.swing.JLabel();
        idRecintoLblER = new javax.swing.JLabel();
        idRecintoFieldER = new javax.swing.JTextField();
        backBtnERPnl = new javax.swing.JButton();
        crearRecintoBtn = new javax.swing.JButton();
        listarRecintosBtn = new javax.swing.JButton();
        modRecintoBtn = new javax.swing.JButton();
        eliminarRecintoBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPnl.setBackground(new java.awt.Color(255, 228, 209));
        backgroundPnl.setPreferredSize(new java.awt.Dimension(768, 578));
        backgroundPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLbl.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        headerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLbl.setText("Seleccione una opcion para Gestionar Recintos");
        backgroundPnl.add(headerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 640, 110));

        crearRecintoPnl.setBackground(new java.awt.Color(255, 255, 255));
        crearRecintoPnl.setPreferredSize(new java.awt.Dimension(710, 440));
        crearRecintoPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerCRLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headerCRLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerCRLbl.setText("Por favor, ingrese los datos del Recinto a crear");
        headerCRLbl.setPreferredSize(new java.awt.Dimension(480, 65));
        crearRecintoPnl.add(headerCRLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        idRecintoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idRecintoLbl.setText("ID del Recinto");
        crearRecintoPnl.add(idRecintoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        idRecintoField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idRecintoField.setPreferredSize(new java.awt.Dimension(91, 22));
        crearRecintoPnl.add(idRecintoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        nombreRecintoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreRecintoLbl.setText("Nombre del Recinto");
        crearRecintoPnl.add(nombreRecintoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        nombreRecintoField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreRecintoField.setPreferredSize(new java.awt.Dimension(91, 22));
        nombreRecintoField.setRequestFocusEnabled(false);
        nombreRecintoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreRecintoFieldActionPerformed(evt);
            }
        });
        crearRecintoPnl.add(nombreRecintoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        ubicacionLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ubicacionLbl.setText("Ubicacion del Recinto");
        crearRecintoPnl.add(ubicacionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        ubicacionField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ubicacionField.setPreferredSize(new java.awt.Dimension(91, 22));
        crearRecintoPnl.add(ubicacionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        capacidadLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        capacidadLbl.setText("Capacidad Maxima del Recinto");
        crearRecintoPnl.add(capacidadLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        capacidadField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        capacidadField.setPreferredSize(new java.awt.Dimension(91, 22));
        crearRecintoPnl.add(capacidadField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        backBtnCRPnl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backBtnCRPnl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/orangeGoBackArrow.png"))); // NOI18N
        backBtnCRPnl.setText("Atras");
        backBtnCRPnl.setPreferredSize(new java.awt.Dimension(128, 30));
        backBtnCRPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnCRPnlActionPerformed(evt);
            }
        });
        crearRecintoPnl.add(backBtnCRPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        backgroundPnl.add(crearRecintoPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        listarRecintosPnl.setBackground(new java.awt.Color(255, 255, 255));
        listarRecintosPnl.setPreferredSize(new java.awt.Dimension(710, 440));
        listarRecintosPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerVELbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headerVELbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerVELbl.setText("***AUN NO CACHO COMO LISTAR WEAS***");
        headerVELbl.setPreferredSize(new java.awt.Dimension(480, 65));
        listarRecintosPnl.add(headerVELbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        idEventoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idEventoLbl.setText("ID del Evento");
        listarRecintosPnl.add(idEventoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        idEventoField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idEventoField.setPreferredSize(new java.awt.Dimension(91, 22));
        listarRecintosPnl.add(idEventoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        idAsistenteLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idAsistenteLbl.setText("ID del Asistente");
        listarRecintosPnl.add(idAsistenteLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(91, 22));
        jTextField1.setRequestFocusEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        listarRecintosPnl.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        nombreAsistLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreAsistLbl.setText("Nombre del Asistente (Nombre, Apellido Paterno)");
        listarRecintosPnl.add(nombreAsistLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        nombreAsistField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreAsistField.setPreferredSize(new java.awt.Dimension(91, 22));
        listarRecintosPnl.add(nombreAsistField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        edadLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edadLbl.setText("Edad");
        listarRecintosPnl.add(edadLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        edadField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edadField.setPreferredSize(new java.awt.Dimension(91, 22));
        listarRecintosPnl.add(edadField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        emailLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailLbl.setText("Emaill");
        listarRecintosPnl.add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        emailField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailField.setPreferredSize(new java.awt.Dimension(91, 22));
        listarRecintosPnl.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        backBtnLRPnl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backBtnLRPnl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/orangeGoBackArrow.png"))); // NOI18N
        backBtnLRPnl.setText("Atras");
        backBtnLRPnl.setPreferredSize(new java.awt.Dimension(128, 30));
        backBtnLRPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnLRPnlActionPerformed(evt);
            }
        });
        listarRecintosPnl.add(backBtnLRPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        backgroundPnl.add(listarRecintosPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        modRecintoPnl.setBackground(new java.awt.Color(255, 255, 255));
        modRecintoPnl.setPreferredSize(new java.awt.Dimension(710, 440));
        modRecintoPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerMRLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headerMRLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerMRLbl.setText("Por Favor, ingrese el ID del Recinto a eliminar");
        headerMRLbl.setPreferredSize(new java.awt.Dimension(480, 65));
        modRecintoPnl.add(headerMRLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 560, -1));

        idRecintoLblMR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idRecintoLblMR.setText("ID del Recinto");
        modRecintoPnl.add(idRecintoLblMR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        idRecintoFieldMR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idRecintoFieldMR.setPreferredSize(new java.awt.Dimension(91, 22));
        modRecintoPnl.add(idRecintoFieldMR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        backBtnMRPnl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backBtnMRPnl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/orangeGoBackArrow.png"))); // NOI18N
        backBtnMRPnl.setText("Atras");
        backBtnMRPnl.setPreferredSize(new java.awt.Dimension(128, 30));
        backBtnMRPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnMRPnlActionPerformed(evt);
            }
        });
        modRecintoPnl.add(backBtnMRPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        backgroundPnl.add(modRecintoPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        eliminarRecintoPnl.setBackground(new java.awt.Color(255, 255, 255));
        eliminarRecintoPnl.setPreferredSize(new java.awt.Dimension(710, 440));
        eliminarRecintoPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerERLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headerERLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerERLbl.setText("**PENDIENTE EXTRA PANEL**Por favor, ingrese el ID del Recinto a modificar");
        headerERLbl.setPreferredSize(new java.awt.Dimension(480, 65));
        eliminarRecintoPnl.add(headerERLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 560, -1));

        idRecintoLblER.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idRecintoLblER.setText("ID del Recinto");
        eliminarRecintoPnl.add(idRecintoLblER, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        idRecintoFieldER.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idRecintoFieldER.setPreferredSize(new java.awt.Dimension(91, 22));
        eliminarRecintoPnl.add(idRecintoFieldER, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        backBtnERPnl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backBtnERPnl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/orangeGoBackArrow.png"))); // NOI18N
        backBtnERPnl.setText("Atras");
        backBtnERPnl.setPreferredSize(new java.awt.Dimension(128, 30));
        backBtnERPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnERPnlActionPerformed(evt);
            }
        });
        eliminarRecintoPnl.add(backBtnERPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        backgroundPnl.add(eliminarRecintoPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        crearRecintoBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        crearRecintoBtn.setText("Crear un Recinto");
        crearRecintoBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        crearRecintoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearRecintoBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(crearRecintoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        listarRecintosBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listarRecintosBtn.setText("Listado de Recintos");
        listarRecintosBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        listarRecintosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarRecintosBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(listarRecintosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        modRecintoBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modRecintoBtn.setText("Modificar Datos de un Recinto");
        modRecintoBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        modRecintoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modRecintoBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(modRecintoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        eliminarRecintoBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eliminarRecintoBtn.setText("Eliminar un Recinto");
        eliminarRecintoBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        eliminarRecintoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarRecintoBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(eliminarRecintoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        add(backgroundPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    //========== BOTONES =======================================================
    
    private void crearRecintoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearRecintoBtnActionPerformed
        crearRecintoPnl.setVisible(true);
        crearRecintoBtn.setVisible(false);
        listarRecintosBtn.setVisible(false);
        modRecintoBtn.setVisible(false);
        eliminarRecintoBtn.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_crearRecintoBtnActionPerformed

    private void listarRecintosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarRecintosBtnActionPerformed
        listarRecintosPnl.setVisible(true);
        crearRecintoBtn.setVisible(false);
        listarRecintosBtn.setVisible(false);
        modRecintoBtn.setVisible(false);
        eliminarRecintoBtn.setVisible(false);
    }//GEN-LAST:event_listarRecintosBtnActionPerformed

    private void modRecintoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modRecintoBtnActionPerformed
        modRecintoPnl.setVisible(true);
        crearRecintoBtn.setVisible(false);
        listarRecintosBtn.setVisible(false);
        modRecintoBtn.setVisible(false);
        eliminarRecintoBtn.setVisible(false);
    }//GEN-LAST:event_modRecintoBtnActionPerformed

    private void eliminarRecintoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarRecintoBtnActionPerformed
        eliminarRecintoPnl.setVisible(true);
        crearRecintoBtn.setVisible(false);
        listarRecintosBtn.setVisible(false);
        modRecintoBtn.setVisible(false);
        eliminarRecintoBtn.setVisible(false);
    }//GEN-LAST:event_eliminarRecintoBtnActionPerformed
    //==========================================================================
    
    
    private void backBtnCRPnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnCRPnlActionPerformed
        // TODO add your handling code here:
        crearRecintoPnl.setVisible(false);
        crearRecintoBtn.setVisible(true);
        listarRecintosBtn.setVisible(true);
        modRecintoBtn.setVisible(true);
        eliminarRecintoBtn.setVisible(true);
    }//GEN-LAST:event_backBtnCRPnlActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void backBtnLRPnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnLRPnlActionPerformed
        // TODO add your handling code here:
        listarRecintosPnl.setVisible(false);
        crearRecintoBtn.setVisible(true);
        listarRecintosBtn.setVisible(true);
        modRecintoBtn.setVisible(true);
        eliminarRecintoBtn.setVisible(true);
    }//GEN-LAST:event_backBtnLRPnlActionPerformed

    private void nombreRecintoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreRecintoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreRecintoFieldActionPerformed

    private void backBtnMRPnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnMRPnlActionPerformed
        modRecintoPnl.setVisible(false);
        crearRecintoBtn.setVisible(true);
        listarRecintosBtn.setVisible(true);
        modRecintoBtn.setVisible(true);
        eliminarRecintoBtn.setVisible(true);
    }//GEN-LAST:event_backBtnMRPnlActionPerformed

    private void backBtnERPnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnERPnlActionPerformed
        eliminarRecintoPnl.setVisible(false);
        crearRecintoBtn.setVisible(true);
        listarRecintosBtn.setVisible(true);
        modRecintoBtn.setVisible(true);
        eliminarRecintoBtn.setVisible(true);
    }//GEN-LAST:event_backBtnERPnlActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtnCRPnl;
    private javax.swing.JButton backBtnERPnl;
    private javax.swing.JButton backBtnLRPnl;
    private javax.swing.JButton backBtnMRPnl;
    private javax.swing.JPanel backgroundPnl;
    private javax.swing.JTextField capacidadField;
    private javax.swing.JLabel capacidadLbl;
    private javax.swing.JButton crearRecintoBtn;
    private javax.swing.JPanel crearRecintoPnl;
    private javax.swing.JTextField edadField;
    private javax.swing.JLabel edadLbl;
    private javax.swing.JButton eliminarRecintoBtn;
    private javax.swing.JPanel eliminarRecintoPnl;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel headerCRLbl;
    private javax.swing.JLabel headerERLbl;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JLabel headerMRLbl;
    private javax.swing.JLabel headerVELbl;
    private javax.swing.JLabel idAsistenteLbl;
    private javax.swing.JTextField idEventoField;
    private javax.swing.JLabel idEventoLbl;
    private javax.swing.JTextField idRecintoField;
    private javax.swing.JTextField idRecintoFieldER;
    private javax.swing.JTextField idRecintoFieldMR;
    private javax.swing.JLabel idRecintoLbl;
    private javax.swing.JLabel idRecintoLblER;
    private javax.swing.JLabel idRecintoLblMR;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton listarRecintosBtn;
    private javax.swing.JPanel listarRecintosPnl;
    private javax.swing.JButton modRecintoBtn;
    private javax.swing.JPanel modRecintoPnl;
    private javax.swing.JTextField nombreAsistField;
    private javax.swing.JLabel nombreAsistLbl;
    private javax.swing.JTextField nombreRecintoField;
    private javax.swing.JLabel nombreRecintoLbl;
    private javax.swing.JTextField ubicacionField;
    private javax.swing.JLabel ubicacionLbl;
    // End of variables declaration//GEN-END:variables
}
