/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Evento;
import Modelo.Asistente;
import Modelo.Menu;
import Exceptions.BadIdAsistenteException;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class GestionEntradasEventos extends javax.swing.JPanel {

    /**
     * Creates new form GestionEntradasEventos
     */
    Asistente newA = new Asistente();
    Menu menu = new Menu();
    
    
    
    public GestionEntradasEventos() {
        initComponents();
        menu.runWea();//PARA TESTEO
        venderEntradasPnl.setVisible(false);
        cancelEntradaPnl.setVisible(false);
        datosAsistentePnl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPnl = new javax.swing.JPanel();
        headerLbl = new javax.swing.JLabel();
        datosAsistentePnl = new javax.swing.JPanel();
        headerVELbl2 = new javax.swing.JLabel();
        idAsistenteLbl = new javax.swing.JLabel();
        idAsistenteField = new javax.swing.JTextField();
        nombreAsistLbl = new javax.swing.JLabel();
        nombreAsistField = new javax.swing.JTextField();
        edadAsistLbl = new javax.swing.JLabel();
        edadAsistField = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        realizarVentaBtn = new javax.swing.JButton();
        venderEntradasPnl = new javax.swing.JPanel();
        headerVELbl = new javax.swing.JLabel();
        idEventoLbl = new javax.swing.JLabel();
        idEventoField = new javax.swing.JTextField();
        backBtnVEPnl = new javax.swing.JButton();
        validarIDEventoBtn = new javax.swing.JButton();
        cancelEntradaPnl = new javax.swing.JPanel();
        headerCELbl = new javax.swing.JLabel();
        idAsistLbl = new javax.swing.JLabel();
        idAsistField = new javax.swing.JTextField();
        backBtnCEPnl1 = new javax.swing.JButton();
        venderEntradasBtn = new javax.swing.JButton();
        CancelarEntradaBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(768, 578));
        setVerifyInputWhenFocusTarget(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPnl.setBackground(new java.awt.Color(255, 228, 209));
        backgroundPnl.setPreferredSize(new java.awt.Dimension(768, 578));
        backgroundPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLbl.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        headerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLbl.setText("Seleccione una opcion para Gestionar las Entradas");
        backgroundPnl.add(headerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 640, 110));

        datosAsistentePnl.setBackground(new java.awt.Color(255, 255, 255));
        datosAsistentePnl.setPreferredSize(new java.awt.Dimension(710, 440));
        datosAsistentePnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerVELbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headerVELbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerVELbl2.setText("Por favor, ingrese los datos del Asistente");
        headerVELbl2.setPreferredSize(new java.awt.Dimension(480, 65));
        datosAsistentePnl.add(headerVELbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        idAsistenteLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idAsistenteLbl.setText("ID del Asistente");
        datosAsistentePnl.add(idAsistenteLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        idAsistenteField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idAsistenteField.setPreferredSize(new java.awt.Dimension(91, 22));
        datosAsistentePnl.add(idAsistenteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        nombreAsistLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreAsistLbl.setText("Nombre del Asistente (Nombre, Apellido Paterno)");
        datosAsistentePnl.add(nombreAsistLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        nombreAsistField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreAsistField.setPreferredSize(new java.awt.Dimension(91, 22));
        nombreAsistField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAsistFieldActionPerformed(evt);
            }
        });
        datosAsistentePnl.add(nombreAsistField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        edadAsistLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edadAsistLbl.setText("Edad");
        datosAsistentePnl.add(edadAsistLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        edadAsistField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edadAsistField.setPreferredSize(new java.awt.Dimension(91, 22));
        edadAsistField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadAsistFieldActionPerformed(evt);
            }
        });
        datosAsistentePnl.add(edadAsistField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        emailLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailLbl.setText("Emaill");
        datosAsistentePnl.add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        emailField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailField.setPreferredSize(new java.awt.Dimension(91, 22));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        datosAsistentePnl.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        realizarVentaBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        realizarVentaBtn.setText("Realizar Venta");
        realizarVentaBtn.setPreferredSize(new java.awt.Dimension(128, 30));
        realizarVentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVentaBtnActionPerformed(evt);
            }
        });
        datosAsistentePnl.add(realizarVentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        backgroundPnl.add(datosAsistentePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        venderEntradasPnl.setBackground(new java.awt.Color(255, 255, 255));
        venderEntradasPnl.setPreferredSize(new java.awt.Dimension(710, 440));
        venderEntradasPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerVELbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headerVELbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerVELbl.setText("Por favor, ingrese del ID del Evento para la venta");
        headerVELbl.setPreferredSize(new java.awt.Dimension(480, 65));
        venderEntradasPnl.add(headerVELbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        idEventoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idEventoLbl.setText("ID del Evento");
        venderEntradasPnl.add(idEventoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        idEventoField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idEventoField.setPreferredSize(new java.awt.Dimension(91, 22));
        venderEntradasPnl.add(idEventoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        backBtnVEPnl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backBtnVEPnl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/orangeGoBackArrow.png"))); // NOI18N
        backBtnVEPnl.setText("Atras");
        backBtnVEPnl.setPreferredSize(new java.awt.Dimension(128, 30));
        backBtnVEPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnVEPnlActionPerformed(evt);
            }
        });
        venderEntradasPnl.add(backBtnVEPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        validarIDEventoBtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        validarIDEventoBtn.setText("Validar ID");
        validarIDEventoBtn.setPreferredSize(new java.awt.Dimension(75, 43));
        validarIDEventoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarIDEventoBtnActionPerformed(evt);
            }
        });
        venderEntradasPnl.add(validarIDEventoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        backgroundPnl.add(venderEntradasPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        cancelEntradaPnl.setBackground(new java.awt.Color(255, 255, 255));
        cancelEntradaPnl.setPreferredSize(new java.awt.Dimension(710, 440));
        cancelEntradaPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerCELbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headerCELbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerCELbl.setText("Por favor, ingrese el ID del Asistente para Reembolsar");
        headerCELbl.setPreferredSize(new java.awt.Dimension(480, 65));
        cancelEntradaPnl.add(headerCELbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        idAsistLbl.setText("ID del Asistente");
        cancelEntradaPnl.add(idAsistLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        idAsistField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idAsistField.setPreferredSize(new java.awt.Dimension(91, 22));
        idAsistField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAsistFieldActionPerformed(evt);
            }
        });
        cancelEntradaPnl.add(idAsistField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        backBtnCEPnl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backBtnCEPnl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/orangeGoBackArrow.png"))); // NOI18N
        backBtnCEPnl1.setText("Atras");
        backBtnCEPnl1.setPreferredSize(new java.awt.Dimension(128, 30));
        backBtnCEPnl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnCEPnl1ActionPerformed(evt);
            }
        });
        cancelEntradaPnl.add(backBtnCEPnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        backgroundPnl.add(cancelEntradaPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        venderEntradasBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        venderEntradasBtn.setText("Vender Entradas para un Evento");
        venderEntradasBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        venderEntradasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderEntradasBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(venderEntradasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        CancelarEntradaBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CancelarEntradaBtn.setText("Cancelar Entrada y Reembolsar Asistente");
        CancelarEntradaBtn.setPreferredSize(new java.awt.Dimension(256, 60));
        CancelarEntradaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarEntradaBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(CancelarEntradaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        add(backgroundPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    //BOTONES
    
    private void CancelarEntradaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarEntradaBtnActionPerformed
        cancelEntradaPnl.setVisible(true);
        venderEntradasBtn.setVisible(false);
        CancelarEntradaBtn.setVisible(false);
    }//GEN-LAST:event_CancelarEntradaBtnActionPerformed

    private void venderEntradasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderEntradasBtnActionPerformed
        venderEntradasPnl.setVisible(true);
        venderEntradasBtn.setVisible(false);
        CancelarEntradaBtn.setVisible(false);
        datosAsistentePnl.setVisible(false);
    }//GEN-LAST:event_venderEntradasBtnActionPerformed
    
    
    //==========================================================================
    
    private void backBtnCEPnl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnCEPnl1ActionPerformed
        cancelEntradaPnl.setVisible(false);
        venderEntradasBtn.setVisible(true);
        CancelarEntradaBtn.setVisible(true);
    }//GEN-LAST:event_backBtnCEPnl1ActionPerformed

    private void idAsistFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAsistFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAsistFieldActionPerformed

    private void backBtnVEPnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnVEPnlActionPerformed
        // TODO add your handling code here:
        venderEntradasPnl.setVisible(false);
        venderEntradasBtn.setVisible(true);
        CancelarEntradaBtn.setVisible(true);
    }//GEN-LAST:event_backBtnVEPnlActionPerformed

    private void nombreAsistFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAsistFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreAsistFieldActionPerformed

    private void edadAsistFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadAsistFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadAsistFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void validarIDEventoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarIDEventoBtnActionPerformed
        //**CODIGO PARA VALIDAR ID EVENTO EXISTE Y ESTA ESCRITO CORRECTAMENTE**
        System.out.println(menu.checkEvento(idEventoField.getText()));
        if(!"".equals(idEventoField.getText()) && menu.checkEvento(idEventoField.getText())){
            idEventoLbl.setVisible(false);
            idEventoField.setVisible(false);
            validarIDEventoBtn.setVisible(false);
            datosAsistentePnl.setVisible(true);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No Existe un Evento asociado a este ID");
        }
    }//GEN-LAST:event_validarIDEventoBtnActionPerformed

    private void realizarVentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVentaBtnActionPerformed
        if (!"".equals(idAsistenteField.getText()) || 
            !"".equals(nombreAsistField.getText()) || 
            !"".equals(edadAsistField.getText()) || 
            !"".equals(emailField.getText())) {
            
            try{
                newA.setidAsistente(idAsistenteField.getText());
            }
            catch(BadIdAsistenteException e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "ID Error", JOptionPane.ERROR_MESSAGE);
            }
            newA.setNombre(nombreAsistField.getText());
            newA.setEdad(Integer.parseInt(edadAsistField.getText()));
            newA.setEmail(emailField.getText());  
        }
        else{
           JOptionPane.showMessageDialog(null, "Los campos se encuentran vacios", "Field Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_realizarVentaBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarEntradaBtn;
    private javax.swing.JButton backBtnCEPnl1;
    private javax.swing.JButton backBtnVEPnl;
    private javax.swing.JPanel backgroundPnl;
    private javax.swing.JPanel cancelEntradaPnl;
    private javax.swing.JPanel datosAsistentePnl;
    private javax.swing.JTextField edadAsistField;
    private javax.swing.JLabel edadAsistLbl;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel headerCELbl;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JLabel headerVELbl;
    private javax.swing.JLabel headerVELbl2;
    private javax.swing.JTextField idAsistField;
    private javax.swing.JLabel idAsistLbl;
    private javax.swing.JTextField idAsistenteField;
    private javax.swing.JLabel idAsistenteLbl;
    private javax.swing.JTextField idEventoField;
    private javax.swing.JLabel idEventoLbl;
    private javax.swing.JTextField nombreAsistField;
    private javax.swing.JLabel nombreAsistLbl;
    private javax.swing.JButton realizarVentaBtn;
    private javax.swing.JButton validarIDEventoBtn;
    private javax.swing.JButton venderEntradasBtn;
    private javax.swing.JPanel venderEntradasPnl;
    // End of variables declaration//GEN-END:variables
}
