/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author MSI
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form GestionEntradas
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(768, 578));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPnl.setBackground(new java.awt.Color(253, 230, 223));
        backgroundPnl.setPreferredSize(new java.awt.Dimension(768, 578));
        backgroundPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/seminar.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        backgroundPnl.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 768, 578));

        add(backgroundPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPnl;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
